version: "3.9"

services:
  database_petlove:
    image: postgres
    container_name: database_petlove
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=petlove
      - POSTGRES_PASSWORD=petlove
      - POSTGRES_DB=petlove
    volumes:
      - pgdata:/data/postgres
#    networks: 
#      - host

#  app:
#    build: .
#    container_name: petlove
#    ports:
#      - 3333:3333
#    volumes:
#      - .:/user/app
#    depends_on: 
#      - database_petlove
#    networks: 
#      - host

volumes:
  pgdata:
    driver: local

#networks:
#  host:
#    name: host
#    external: true